### ISSUE TITLE
Объяснение входных данных

### ISSUE THREAD

**Issue by AlexLuik** [aktivgo/SimplexMethod#1]
В каком формате принимаются входные данные? Можно пример. Был бы очень признателен

**Comment by aktivgo** [comment]
Привет @AlexLuik 

Данные подаются в таком виде
![image](https://user-images.githubusercontent.com/82175542/201964752-98523b16-338d-41bb-bc5d-0147dcfdde74.png)

Вот пара тестовых данных:
_2 1
max
4 5 <= 20
3 -3 <= 13
1 2 >= 2
1 0 >= 0
0 1 >= 0_

_2 1 0 0 0 0 0
max
0 1 0,2 0 0 -0,79 0 = 0,8
0 0 0,39 0 1 -0,58 0 = 3,58
1 0 0 0 0 1 0 = 4
0 0 0,58 1 0 -5,26 0 = 3,32
0 0 0,2 0 0 0,21 -1 = 0,8
1 0 0 0 0 0 0 >= 0
0 1 0 0 0 0 0 >= 0
0 0 1 0 0 0 0 >= 0
0 0 0 1 0 0 0 >= 0
0 0 0 0 1 0 0 >= 0
0 0 0 0 0 1 0 >= 0
0 0 0 0 0 0 1 >= 0_

[task3_1.txt](https://github.com/aktivgo/SimplexMethod/files/10014178/task3_1.txt)
[task3_2.txt](https://github.com/aktivgo/SimplexMethod/files/10014182/task3_2.txt)
[task3_3.txt](https://github.com/aktivgo/SimplexMethod/files/10014183/task3_3.txt)
